#pragma once

enum class PacketType
{
    GAME_SEED = 1,
    SKIP_INTRO = 2,
    PLAYER_INDEX = 3,
    CLIENT_READY = 4,
    CARD_PLAY = 10,
    CARD_DRAW = 11,
    CARD_DISCARD = 12,
    CONFIRMATION = 20,
    YES_OR_NO = 21,
    NUMBER_CHOICE = 22,
    OPTION_CHOICE = 23,
    CHOOSE_CARD_FROM_HAND = 24,
    CHOOSE_CARD_FROM_ACTIVE_CARDS = 25,
    CHOOSE_CARD_FROM_DISPLAYED_CARDS = 26,
    CHOOSE_CARD_FROM_GRAVEYARD = 27,
    CHOOSE_DECK = 28,
    PLAY_CARDS_DONE = 29,
    DRAW_CARDS_DONE = 30,
    DISCARD_CARDS_DONE = 31,
};